### ISSUE TITLE
Getting this error on hot restarting

### ISSUE THREAD

**Issue by Kapish26** [FengChendian/serial_port_win32#19]
```
The following _Exception was thrown while handling a gesture:
Exception: Last error is 0

When the exception was thrown, this was the stack: 
#0      SerialPort.open (package:serial_port_win32/src/serial_port.dart:169:11)
#1      _MyHomePageState._getPortsAndOpen (package:demo/main.dart:43:14)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#18     _invoke1 (dart:ui/hooks.dart:170:10)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#774c2
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(1212.8, 640.8)
  finalLocalPosition: Offset(19.2, 30.4)
  button: 1
  sent tap down
====================================================================================================
```

**Comment by FengChendian** [comment]
Emm... I think it's just a UI async error, not caused by serial port.
