### ISSUE TITLE
Failed to load dynamic library 'advapi32.dll'.  while I am looking for available ports.

### ISSUE THREAD

**Issue by SherazAsghar37** [FengChendian/serial_port_win32#30]
════════ Exception caught by gesture ═══════════════════════════════════════════
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library 'advapi32.dll': dlopen failed: library "advapi32.dll" not found

When the exception was thrown, this was the stack
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _advapi32
advapi32.g.dart:22
#3      _advapi32 (package:win32/src/win32/advapi32.g.dart)
advapi32.g.dart:1
#4      _RegOpenKeyEx
advapi32.g.dart:1530
#5      _RegOpenKeyEx (package:win32/src/win32/advapi32.g.dart)
advapi32.g.dart:1
#6      RegOpenKeyEx
advapi32.g.dart:1528
#7      SerialPort._getRegistryKeyValue
serial_port.dart:559
#8      SerialPort.getAvailablePorts
serial_port.dart:628
#9      _MyHomePageState._getPortsAndOpen
main.dart:43
#10     _InkResponseState.handleTap
ink_well.dart:1154
#11     GestureRecognizer.invokeCallback
recognizer.dart:275
#12     TapGestureRecognizer.handleTapUp
tap.dart:654
#13     BaseTapGestureRecognizer._checkUp
tap.dart:311
#14     BaseTapGestureRecognizer.acceptGesture
tap.dart:281
#15     GestureArenaManager.sweep
arena.dart:167
#16     GestureBinding.handleEvent
binding.dart:469
#17     GestureBinding.dispatchEvent
binding.dart:445
#18     RendererBinding.dispatchEvent
binding.dart:331
#19     GestureBinding._handlePointerEventImmediately
binding.dart:400
#20     GestureBinding.handlePointerEvent
binding.dart:363
#21     GestureBinding._flushPointerEventQueue
binding.dart:320
#22     GestureBinding._handlePointerDataPacket
binding.dart:293
#23     _invoke1 (dart:ui/hooks.dart:158:13)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#589d5
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(319.7, 685.7)
    finalLocalPosition: Offset(31.7, 21.7)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

**Comment by FengChendian** [comment]
This is a bug caused by win32 package. The DLL library is lost in your system.

Please go to https://github.com/dart-windows/win32 to find help.
