### ISSUE TITLE
not working in android

### ISSUE THREAD

**Issue by Mrrsh2000** [FengChendian/serial_port_win32#7]
```
The following ArgumentError was thrown attaching to the render tree:
Invalid argument(s): Failed to load dynamic library 'advapi32.dll': dlopen failed: library "advapi32.dll" not found

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      _advapi32 (package:win32/src/advapi32.dart:20:34)
#3      _advapi32 (package:win32/src/advapi32.dart)
#4      _RegOpenKeyEx (package:win32/src/advapi32.dart:947:28)

```
When running it on Android, we encounter a high error. What is the offer?

**Comment by FengChendian** [comment]
This is a serial port package using win32 API. Win32 package only supported windows. So this package only supported windows too.

**Comment by Mrrsh2000** [comment]
oh thanks ♥
